# Default values for todo-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: hungvietlai/my_todo_app
  tag: latest

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

labels:
  app: my-todo-app


